# Generated by Django 5.2.10 on 2026-02-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingJournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("Symbol", models.CharField(max_length=255)),
                (
                    "Market_Bias",
                    models.CharField(max_length=255, verbose_name="Market Bias"),
                ),
                (
                    "Setup_Strategy",
                    models.CharField(max_length=255, verbose_name="Setup Strategy"),
                ),
                (
                    "Option_Type",
                    models.CharField(max_length=255, verbose_name="Option Type"),
                ),
                ("Strike", models.CharField(max_length=255, verbose_name="Strike")),
                ("Entry", models.DecimalField(decimal_places=2, max_digits=6)),
                ("Stop", models.DecimalField(decimal_places=2, max_digits=6)),
                ("Target", models.DecimalField(decimal_places=2, max_digits=6)),
                ("Outcome", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "Rule_Adherence",
                    models.CharField(max_length=255, verbose_name="Rule Adherence"),
                ),
                (
                    "Entry_Quality",
                    models.PositiveIntegerField(verbose_name="Entry Quality"),
                ),
                (
                    "Emotional_State",
                    models.CharField(max_length=255, verbose_name="Emotional State"),
                ),
                (
                    "Why_this_trade",
                    models.CharField(max_length=255, verbose_name="Why this trade"),
                ),
                (
                    "Chart_Screenshot",
                    models.CharField(max_length=255, verbose_name="Chart Screenshot"),
                ),
            ],
        ),
    ]
